<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (c) Brian Matthews, 2023.
All rights reserved.

Proprietary and confidential
Unauthorized copying of this file, via any medium is strictly prohibited
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation=" http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.github.bmatthews68</groupId>
    <artifactId>cookbook</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>Containers for Java - Docs</name>
    <build>
        <plugins>
            <plugin>
                <groupId>org.asciidoctor</groupId>
                <artifactId>asciidoctor-maven-plugin</artifactId>
                <version>3.2.0</version>
                <executions>
                    <execution>
                        <id>book</id>
                        <phase>package</phase>
                        <goals>
                            <goal>process-asciidoc</goal>
                        </goals>
                        <configuration>
                            <sourceDirectory>${basedir}/src/docs/asciidoc</sourceDirectory>
                            <backend>pdf</backend>
                            <embedAssets>true</embedAssets>
                            <standalone>true</standalone>
                            <attributes>
                                <imagesdir>${basedir}/src/docs/asciidoc/images</imagesdir>
                                <pdf-fontsdir>uri:classloader:fonts</pdf-fontsdir>
                                <doctype>book</doctype>
                                <icons>font</icons>
                                <pagenums/>
                                <idprefix/>
                                <idseparator>-</idseparator>
                                <revnumber>${project.version}</revnumber>
                                <revdate>${maven.build.timestamp}</revdate>
                                <organization>Brian Matthews</organization>
                            </attributes>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.asciidoctor</groupId>
                        <artifactId>asciidoctorj</artifactId>
                        <version>3.0.1</version>
                    </dependency>
                    <dependency>
                        <groupId>org.asciidoctor</groupId>
                        <artifactId>asciidoctorj-pdf</artifactId>
                        <version>2.3.23</version>
                    </dependency>
                    <dependency>
                        <groupId>org.jruby</groupId>
                        <artifactId>jruby</artifactId>
                        <version>9.4.15.0</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
</project>
