= Beef Plov

*Original:* https://natashaskitchen.com/beef-plov-beef-rice-pilaf-recipe/

== Ingredients

[%autowidth,frame=none,grid=none]
|===
| 700 g | Beef chuck, beef sirloin or good quality beef stew meat
| &#8531; cup | canola oil, or extra light olive oil (not extra virgin)
| 2 | medium onions, finely chopped
| 3 | medium carrots, cut into matchsticks or grated
| 1 tsp | salt for the meat and veggies
| 1&#189; tsp | salt for the rice
| &#189; tsp | freshly ground black pepper
| 1 tsp | paprika
| 1 tsp | cumin
| 3-4 | bay leaves
| 1&#190; cups | hot water for braising meat
| 3 cups | long grain rice (Basmati or Jasmin rice work great!)
| 4 cups | hot water when cooking rice
| 1 head | garlic
| 1 tsp | ground coriander
|===

== Method

. Trim beef of excess fat and sinews (aka the chewy stuff), pat the meat dry with a paper towel and chop into 1.2 cm to 1.9 cm pieces.

. Preheat your Dutch oven (or your large soup pot with a heavy bottom), to high heat.
Once it’s hot, stir in your &#8531; cup canola oil.
Once oil is hot, add chopped meat and sauté uncovered 7 min over high heat until meat is browned, stirring every minute or so, so it doesn’t scorch to the bottom of the pan.
+
[NOTE]
It’s important to preheat the Dutch oven first for the meat to sear over very high heat, otherwise it will juice out and become dry.

. Reduce heat to medium and Add chopped onion, stirring often until onion is softened (5 minutes). Stir in sliced carrots, 1 tsp salt, &#189; tsp pepper, 1 tsp paprika, 1 tsp cumin, 3-4 bay leaves and continue to cook over medium heat 5 minutes until carrots are softened.

. Add 1&#190; cups hot water, cover & simmer over medium/low heat 45 min or until meat is tender.

. Meanwhile, rinse rice until water runs clear, then drain and set aside (this gets rid of the starch so you won’t end up with a sticky rice).

. Spread rice over the meat and add 4 cups hot water. Sprinkle the rice with 1&#189; tsp salt and lightly stir to break up any clumps in the rice, bring to a boil then reduce heat to low and Let cook uncovered until most of the water is absorbed (10 min).

. Cut off the base of your whole garlic head to expose the cloves. Put your head of garlic, cut side down into the centre of the rice and sprinkle the top of the rice with 1 tsp ground coriander

. Poke 7-10 holes through the rice to allow steam to escape to the surface,  reduce the heat to low, then cover and cook an additional 15 minutes or until rice is cooked through. Remove the garlic head and bay leaves and stir everything gently to combine.