= Chilli Con Carne

== Ingredients

[%autowidth,frame=none,grid=none]
|===
| 1 | large onion (small dice)
| 1 | red pepper (chopped)
| 2 cloves | garlic (finely chopped)
| 1 tbsp | oil
| 1 tsp | hot chilli powder (heaped)
| 1 tsp | paprika
| 1 tsp | ground cumin
| 500 g | lean minced beef
| 1 | beef stock cube
| 400g | chopped tomatoes (1 can)
| &#189; tsp | dried majoram
| 1 tsp | sugar
| 2 tbsp | tomato purée
| 410 g | red kidney beans (1 can)
|===

== Method

. Heat 1 tsp of oil in pan over medium heat.

. Add onion to pan and cook for 5 minutes until onion is soft. Stir frequently while cooking.

. Stir garlic, red pepper, 1 tbsp (heaped) of chilli powder, 1 sp of paprika and 1 tsp of ground cumin into the onion and cook for another 5 minutes.

. Brown 500 g minced beef for about 5 minutes over a medium high heat and break up lumps with spatula.

. Crumble 1 beef stock cube into 300 ml hot water and pour into the beef mix on the pan.

. Add 400g can of chopped tomatoes, &#189; tsp of dried marjoram, 1 tsp of sugar, salt and pepper, and 2 tbsp of tomato purée and stir well.

. Bring to boil, turn down heat and allow to simmer for 20 minutes covered. Stir periodically. If the sauce starts to dry out then add a little water.

. Drain and rinse 410 g can of red kidney beans in a sieve and stir them into the chilli pot. Bring to boil again and simmer for another 10 minutes uncovered.

. Add extra salt and pepper if required.

. Cover and let stand for 10 minutes before serving.

Serve with long grained rice and soured cream.