= Chicken Cordon Bleu

== Ingredients

[%autowidth,frame=none,grid=none]
|===
| 2 | chicken breast
| 50g | swiss cheese
| 100g | ham
| 50g | panko bread crumbs
| 40g | flour
| 1 tsp | garlic powder
| | Salt and pepper to taste
| 2 | eggs (beaten)
| | Salad to serve
|===

== Method

. Start by butterflying the chicken breasts by carefully running your knife down the side of the breast. Once you're &#190; of the way through, open up the chicken breasts, it should look like a love heart.

. Place the chicken breast between two pieces of parchment paper and use a kitchen mallet or small saucepan to pound the chicken so it's nice and flat and even.

. With the smoothest side of the chicken breasts facing down, lay on your sliced ham and sliced cheese.

. Then roll the chicken breast up until you create a cylindrical log.

. Get your breading station ready by placing the eggs in one bowl, the breadcrumbs in another and the flour in the third one. Add the garlic powder, salt and pepper to the flour and mix well.

. Take your rolled chicken breasts and dust in the flour, followed by a dip in the egg mixture and finally roll in the breadcrumbs.

. Place the crumb chicken breasts onto a lined baking tray and bake at 180&#176;C for 25-30 minutes, or until golden and cooked through. If using a thermometer, you're looking for an internal temperature of 70&#176;C

. Served with mash potato and I like mine with a little bit of mustard.