= Classic Slow Cooker Chilli

== Ingredients

[%autowidth,frame=none,grid=none]
|===
| 900 g | lean ground beef
| 1 | large onion (diced)
| 3 cloves | garlic (minced)
| 2 tsp | cumin powder
| 2&#189; tbsp | chilli powder
| 1 tsp | garlic powder
| 1 tsp | dried oregano
| 1&#189; tsp | salt
| &#189; tsp | black pepper
| &#189; tsp | cayenne pepper
| 425 g | black beans (drained & rinsed) (1 can)
| 850 g | kidney beans (drained & rinsed) (2 cans)
| 425 g | diced tomatoes (with their juice) (1 can)
| 283 g | tomatoes and green chillis (with their juice)
| 850 g | tomato sauce (2 cans/jars)
|===

== Method

. Sauté the beef in a skillet over a medium high heat until it releases the fat (4 - 5 minutes), breaking up the beef with a spatula.

. Add onion to the skillet and sauté until tender (4 - 5 minutes).

. Add minced garlic, cumin, chilli powder, garlic powder, dried oregano, salt, pepper and cayenne pepper and cook for about 30 seconds stirring constantly.

. Transfer beef to slow cooker.

. Add remaining ingredients (black beans, kidney beans, diced tomatoes, tomatoes and green chillis, and tomato sauce) to the slow cooker.

. Stir to combine and cook on low for 6 - 8 hoursfootnote:[Or cook on high for 3 -4 hours.].