= Classic Steak au Poivre

== Ingredients

[%autowidth,frame=none,grid=none]
|===
| 4 x 170 - 255 g | boneless medallion steaks (e.g. filet mignon)
| | kosher salt
| 30 g | whole black pepper corns
| 3 tbsps | vegetable oil
| 1 tbsp | butter (unsalted)
| 2 sprigs | thyme
| 1 clove | garlic
| &#189; | large shallot (minced)
| 2 tbsps | brandy or cognac
| &#190; cup | chicken stock / broth
| &#190; cup | heavy cream (or 6 tablespoons crème fraîche)
| 1 tsp | Dijon mustard
|===

== Method

. Season steaks all over with kosher salt place uncovered in the refrigerator to air dry for 30 minutes.

. Crack pepper corns in halves and quartersfootnote:[coarsest setting on a pepper mill].

. Preheat oven to 375&#176;C.

. Press one side of each steak down on to the cracked pepper corns to get an even coating. Do not discard the left-over pepper.

. Heat skillet to medium high heat. Add steak pepper corn coated side down and toast for about 3 minutes to form a crust.

. Turn the steaks over and add butter, thyme and garlic to the pan. Cook the steaks until seared on second side basting with the pan sauce.

. Remove pan from heat. Take the steaks and put them on a baking sheet in a rimmed tray, Check temperature (52&#176C; is medium rare). If not at final temperature place into oven until done.

. Remove from oven when done and allow to rest for at least 5 minutes.

. Pour off all but 1 tbsp of fat from the skillet and discard garlic and thyme.

. Add shallot and any reserved cracked pepper corns. Return to medium heat and cook until shallots are tender (about 2 minutes).

. Add brandy or cognac and cook until raw alcohol smell is burned off.

. Add chicken stock and bring to simmer, then whisk in cream or crème fraîche) then simmer until sauce judt glazes a spoon. Whisk in mustard and season with salt.

 Serve with French fries, mashed potatoes and vegetables.