= Grilled chicken, sun-dried tomato, pasta salad

== Ingredients

[%autowidth,frame=none,grid=none]
|===
| 2 | large chicken breasts
| 1 tbsp | smoked paprika
| 1 tsp | garlic powder
| 1 tsp | Sea salt
| 1 tsp | cracked black pepper
| 2 | zucchini
| 500 g | orecchiette
| 100 g | sun-dried tomatoes in oil
| 30g | grated parmesan cheese
| 1 clove | garlic
| 30g | walnuts (toasted)
| &#188; cup | water
| 1 | handful fresh basil leaves
| 1 | lemon (juiced)
|===

== Method

. Preheat the oven grill (broiler) to 200&#176;C.

. Toss the chicken with 30 ml of the olive oil, the paprika, garlic powder and a large pinch of salt and black pepper in a large bowl until well combined.

. Transfer the chicken to a wire rack over a lined oven tray and place under the grill.

. Cook for 15 - 18 minutes, until browned and the internal temperature reaches 62&#176;C.

. While the chicken is cooking, bring a large saucepan of salted water to the boil over high heat.

. Slice the zucchini lengthways into quarters and cut out the core.

. Dice the zucchini into roughly the same size as the pasta.

. Once the water is boiling, add the orecchiette and cook for 6 minutes, then add the zucchini and cook for a further 2 minutes.

. Drain and rinse under cold water to stop it cooking and sticking together. Set it aside.

. While the pasta is cooking, combine the sun-dried tomatoes in their oil, parmesan, garlic, walnuts and the remaining 40ml olive oil in a small food processor.

. Season with some salt and process until a rough purée. Add the water and process again until smooth. Set aside.

. When the chicken is cooked, allow it to rest for 5 minutes before slicing.

. In a large serving bowl, toss the pasta with zucchini, sun-dried tomato pesto, torn basil leaves and lemon juice.

. Top with the sliced chicken and serve.