= Gyoza

== Ingredients

[%autowidth,frame=none,grid=none]
|===
2+a|
[discrete]
=== Wrappers
| 240 g | plain flour
| &#189; tsp | salt
| 120 ml | hot water (just boiled)
2+a|
[discrete]
=== Filling
| 1&#189; cups | green cabbage (finely chopped)
| 1 tsp | salt
| 500 g | pork (minced)
| 1 cup | garlic chives (finely chopped)
| 1 clove | garlic (crushed)
| 1 tsp | ginger (grated)
| 1 tsp | sesame oil
| 1 tbsp | cornstarch / corn flour
| 2 tsp | soy sauce
2+a|
[discrete]
=== Dipping sauce
| | soy sauce
| | rice wine vinegar
| | Chilli oil (Rayu)
|===

== Method

=== Wrappers

. Dissolve salt in hot water.

. Slowly add and mix water into flour.

. Mix into a dough ball.

. Knead for 10 minutes.

. Split in half.

. Roll each half into 4 cm logs, wrap in cling film, and rest for 30 minutes.

== Filling

. Combine cabbage and &#189; tsp salt in small bowl. Set aside for 20 minutes to allow the cabbage to wilt slightly.

. Place remaining filling ingredients (including remaining &#189; tsp salt) in a large bowl. Squeeze out any excess water from the cabbage and then add it to the larget bowl.

. Mix the filling by hand.

. Sprinkle baking tray with 1 tsp of cornstarch / corn flour.

. Place 1 gyoza wrapper in left palm. Dip finger in water and run it along the edge of the wrapper. Place one slightly heaped tbsp of filling on the wrapper. Fold over wrapper and press edges to seal. Make about 4 pleats.

. Heat 1 tbsp oil in a large skillet (that has a lid) over medium high heat.

. Place about 12 gyoza in rows, slightly overlapping each other. Cook until the underside is light golden, then pour 1/3 cup of water around the gyoza and place the lid on.

. Cook until the water has completely evaporated (so the golden underside is not wet and soggy) and the wrapper is slightly translucent on top – about 3 to 4 minutes.

. Use an egg flip to transfer onto a plate upside down i.e. golden side up.
Serve with Dipping Sauce.

. Serve each ingredient separately so people can mix according to their taste. I use about equal portions of soy sauce and vinegar with a generous splash of chili oil.