= One pot sausage and rice

== Ingredients

[%autowidth,frame=none,grid=none]
|===
| 1 | onion
| 1 | carrot
| 1 | stick celery
| 2 cloves | garlic
| 2 | chorizo sausages
| 2 tbsp | olive oil
| &#189; tsp | smoked paprika
| | salt and pepper to taste
| 120 g (4.2 oz) | arborio rice
| 500 ml (17½ oz) | chicken stock
| 60 g (2.1 oz) | baby spinach
|===

=== Method

. Peel and finely dice the onion and carrot, finely dice the celery then set aside.

. Crush and roughly chop the garlic, then set aside.

. Slice the chorizo into chunks, (3 - 4 cm thick) then set aside.

. Add olive oil to a medium sized saucier. Preheat the saucier on high heat for 30 seconds.

. Add the onion, carrot and celery, sweat for 2-3 minutes with ½ tsp of salt. Once the onions turn translucent, add the garlic and stir.

. Add the sliced chorizo and stir into the vegetables. Cook for two minutes or until the fat begins to render out of the chorizo.

. Add the smoked paprika, ¼ tsp of salt, 12 cracks of black pepper and the rice (no need to rinse the rice). Keep the saucier on the heat to lightly toast the rice for 1 minute.

. Add the chicken stock and stir, making sure to lift any pieces of rice stuck to the bottom of the saucier. Bring the stock to a simmer then turn the element down to low, place a lid on top and leave for 15 minutes.

. Remove the lid and check the rice is soft. If the rice is still firm, place the lid back on and leave on low heat for a further 5 minutes.

. Remove the lid, turn the heat up high and add the spinach. Place the lid back on for 60 seconds. Remove the lid, stir the rice and cook for a further 60 seconds.

. Taste the rice and adjust seasoning if required. Plate and enjoy.