= Potatoes au Gratin (Dauphinoise)

== Ingredients

[%autowidth,frame=none,grid=none]
|===
| 375 ml | full-fat cream
| 2 cloves | garlic (minced)
| 2 tbsp (30g) | unsalted butter (melted)
| 1.25 kg / 2.5 lb | starchy potatoesfootnote:[Russet, Sebago, Maris Piper]
| 1 tsp | salt
| &#188; tsp | pepper
| 250 g | gruyere cheesefootnote:[Or colby, cheddar, havarti, tasty] (freshly grated)
| 2 tsp | thyme leaves
|===

== Method

. Pre-heat oven to 180&#176;C.

. Slice potatoes using mandolin.

. Place melted butter, cream and garlic in a jug and mix until combined.

. Make a layer with &#8531; of potatoes, pour over &#8531; of the cream mixture, sprinkle &#8531; tsp of salt, and &#8531; of the black pepper, some thyme, and &#190; cups of cheese.

. Make the second layer the same as the first.

. For the third layer omit the cheese at this stage.

. Cover with foil and bake for 1 hour 15 minutes. Use a knife to test that the potatoes in the middle are soft. If not cook for longer in 15 minute increments.

. Remove foil, top with remaining cheese and bake for an additional 10 to 15 minutes. Rest for 5 minutes before serving.