= Pumpkin Soup

== Ingredients

[%autowidth,frame=none,grid=none]
|===
| 1.2 kg | pumpkin (any type) OR butternut squash, unpeeled weight
| 1 | onion , sliced (white, brown, yellow)
| 2 cloves | garlic , peeled whole
| 3 cups | vegetable or chicken broth/stock , low sodium
| 1 cup | water
| | Salt and pepper
| &#189; – &#190; cup | cream , half-and-half or milk
|===

== Method

. Cut the pumpkin into 3 cm slices.
Cut the skin off and scrape seeds out.
Cut into 4 cm chunks.

. Place the pumpkin, onion, garlic, broth and water in a pot – liquid won't quite cover all the pumpkin.
Bring to a boil, uncovered, then reduce heat and let simmer rapidly until pumpkin is tender (check with butter knife) – about 10 minutes.

. Remove from heat and use a stick blender to blend until smooth.

. Season to taste with salt and pepper, stir through cream (never boil soup after adding cream, cream will split).

*Serving:* Ladle soup into bowls, drizzle over a bit of cream, sprinkle with pepper and parsley if desired.
Serve with crusty bread!