= Slow Cooker Pork Casserole

== Ingredients

[%autowidth,frame=none,grid=none]
|===
| 1 tbsp | vegetable or rapeseed oil
| 4 | pork shoulder steaks (about 750 g) cut into large chunks
| 1 | onion (chopped)
| 1 | leek (chopped)
| 1 | carrot (chopped)
| 1 | chicken stock cube
| 2 | bay leaves
| 3 | sage leaves
| 4 | springs of thyme
| 2 tsp | Dijon mustard
| 1 tbsp | cider vinegar
| 2 tsp | cornflour
| 1 tbsp | honey
|===

== Method

. Season the pork with salt and pepper.

. Heat oil in skillet over a high heat and search the pork chunks until they are a deep brown all over.

. Transfer pork to slow cooker.

. Add onions and leeks to the skillet and cook for a few minutes util they soften.

. Add a splash of water and scrape the bottom of the skillet clean before tipping the onions and leeks into the slow cooker.

. Add carrot, herbs (bay leaves, sage leaves and sprigs of thyme tied together), stock cube, mustard, vinegar, salt and pepper. Add water to cover the contents of slow cooker. Cook on low for 6 - 8 hoursfootnote:[Or high for 5 - 6 hours].

. In a saucepan, mix the cornflour and honey with 1 - 2 tsp of the liquid from the slow cooker until you have smooth paste.

. Add 100 ml more liquid and bring to a simmer until thickened.

. Then stir the mix back into the slow cooker.

Serve with mashed potatoes or dumplings.